### ISSUE TITLE
Infografia

### ISSUE THREAD

**Issue by FedericoVictorianoSierra** [FedericoVictorianoSierra/MatematicasDisA#2]
Realizar infografía de los sistemas numérico

**Comment by mariagfh1228** [comment]
Ya terminé la infografía

**Comment by mariagfh1228** [comment]
![IMG-20200926-WA0074.jpg](https://user-images.githubusercontent.com/71904967/94400148-3d176980-012e-11eb-9594-2c447a63ebbe.jpg)

**Comment by FedericoVictorianoSierra** [comment]
[Uploading Infografia de Sitemas Numericosl (Federico Victoriano Sierra (1AISC)).pdf…]()

**Comment by OFELHER93** [comment]
ya termine mi infografia omar felipe hernendez

[Uploading INFO.pdf…]()
