### ISSUE TITLE
Practica de Conjuntos, subconjuntos y producto

### ISSUE THREAD

**Issue by FedericoVictorianoSierra** [FedericoVictorianoSierra/MatematicasDisA#30]
- [x] Federico
- [x] Guadalupe
- [x] Omar
- [ ] Itzel

**Comment by OFELHER93** [comment]
PRACTICA OPERACIONES
[Operacion conjunto y plano cartesiano omar.pdf](https://github.com/FedericoVictorianoSierra/MatematicasDisA/files/5450141/Operacion.conjunto.y.plano.cartesiano.omar.pdf)

**Comment by mariagfh1228** [comment]
EJERCICIOS 1 UNIDAD II
[OPERACIONES DE CONJUNTOS, SUBCONJUNTOS  Y PLANO CARTESIANO.pdf](https://github.com/FedericoVictorianoSierra/MatematicasDisA/files/5450157/OPERACIONES.DE.CONJUNTOS.SUBCONJUNTOS.Y.PLANO.CARTESIANO.pdf)

**Comment by FedericoVictorianoSierra** [comment]
[Uploading Practica de Conjuntos, subconjuntos y producto(Federico Victoriano Sierra (1AISC)).pdf…]()
