### ISSUE TITLE
Practica de relaciones y funciones

### ISSUE THREAD

**Issue by FedericoVictorianoSierra** [FedericoVictorianoSierra/MatematicasDisA#31]
- [x] Federico
- [x] Guadalupe
- [x] Omar
- [ ] Itzel

**Comment by FedericoVictorianoSierra** [comment]
[Uploading Relaciones y funciones (Federico Victoriano Sierra (1AISC)).pdf…]()

**Comment by OFELHER93** [comment]
[Uploading Practica 2 Relaciones y Funciones  omar.pdf…]()

**Comment by mariagfh1228** [comment]
[Practica 2 Relaciones y Funciones.pdf](https://github.com/FedericoVictorianoSierra/MatematicasDisA/files/5557045/Practica.2.Relaciones.y.Funciones.pdf)
